name: Create a comment on new issues

on: 
  issues:
    types: [opened] 
      
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{toJSON(github.event)}}' | jq
        shell: bash  
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi,
              Thank you for reporting this issue :raised_hands: We'll look into this shortly!
              If this is a security alert kindly report it to securityalert@openappsec.io :exclamation:
              If this is a feature request we recommend creating a discussion instead:bulb:
            
            
