on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    #permissions:
      #contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create asset
        run: |
           zip --junk-paths my-artifact Dockerfile
      - name: create release     
        uses: ncipollo/release-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v2.0.0.0
          name: test new action
          draft: true
          artifacts: ./my-artifact.zip
          
          
      
     
          

